### ISSUE TITLE
vagrant up results in: Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145

### ISSUE THREAD

**Issue by hems** [OpenBazaar/OpenBazaar#1004]
````vagrant up```` finished with

==> default: MongoDB shell version: 2.4.9
==> default: connecting to: test
==> default: Tue Nov 11 21:29:02.520 Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
==> default: exception:
==> default: connect failed

**Comment by hoffmabc** [comment]
Mongo is now deprecated and this is an old version so closing.
