### ISSUE TITLE
Seeing only the seed nodes after upgrade to 3.0

### ISSUE THREAD

**Issue by GoodPerson71** [OpenBazaar/OpenBazaar#1009]
I used to run it from a VPS with nohup sudo bash run.sh -j -q 8888 & as per the instructions from the site and it was working and seeing 10s of stores.
After the upgrade I ran it with nohup sudo bash ./openbazaar start -j -q 8888 &
and see only the seeds and it's been like couple of days now, with few restarts and trying some variations.

I might very well be doing something wrong though.

**Comment by hoffmabc** [comment]
This should be resolved in 0.4
