### ISSUE TITLE
Change order of signing among buyer and seller to remove a step

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1025]
Correct me if I'm wrong, but here's how I believe signing for the release of multisig funds works right now:

1. After multisig creation, the seller enters his Bitcoin address when he marks as shipped but doesn't make a proposed transaction or sign it.

2. The buyer makes the proposed transaction from multisig to seller, and the first signature when they hit "Release Payment".

3. The seller receives this message, and if they've received the product then they make the second signature and release payment.

Aren't we adding an unnecessary step? Right now, the buyer and seller both need to be online for payment to be finalized because the buyer can only send the message if the seller is online to make the final signature. This is causing problems. Instead, we can do the following:

1. After multisig creation, the seller enters his Bitcoin address when he marks as shipped, makes a proposed transaction from multisig to himself and signs it.

2. The buyer receives this message, and if they've received the product they sign off on the proposed transaction, releasing funds when they hit "Release Payment".

3. There is no step 3 because the seller already signed and they don't need to be online any more.

**Comment by hoffmabc** [comment]
Didn't we complete this @SamPatt ?

**Comment by SamPatt** [comment]
Yes you fixed this a while ago, well done. I'm closing.
