### ISSUE TITLE
continued connectivity issues after troubleshooting steps

### ISSUE THREAD

**Issue by theblacksquid** [OpenBazaar/OpenBazaar#1039]
OS: Ubuntu 14.04
Browser: Mozilla Firefox
Severity: Moderate

I've already figured out how to port forward port 12345 on my router, and disabled UPnP using -j (even though my router is UPnP compliant, and it works, seeing my Bittorrent client is online just fine), I even tried loading up OB using 

    ./openbazaar --disable-open-browser --http-port 8888 --disable-stun-check -j --server-ip xxx.xxx.xxx.xxx start

These fixes seem to be working for everyone else, So I must be doing something wrong.

**Comment by hoffmabc** [comment]
Is this an issue still @theblacksquid @ABISprotocol ?

**Comment by drwasho** [comment]
@hoffmabc I think we could probably close this considering this is an Issue referencing an older and deprecated version of the client.
