### ISSUE TITLE
Discussion: HD keys for signing?

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1045]
Right now signing of multisig funds is done with the same key over and over. This leads to privacy concerns because once a user signs a transction, anyone else can see all future multisig transactions they are engaged in.

To avoid this, we could use HD keys, and never use the same keys twice. Alternatively, we can just create a new key for each trade, though I think HD means easier key management.

**Comment by drwasho** [comment]
@hoffmabc can we close this?
