### ISSUE TITLE
Missing libzmq-dev dependency

### ISSUE THREAD

**Issue by enjoyaol** [OpenBazaar/OpenBazaar#1049]
On fresh ubuntu install, during the pip install -r requirements.txt step, compilation of pyzmq 14.3.1 partially fails because libzmq-dev is missing. I guess we should add this dependency in the apt-get section of installUbuntu function of this script configure.sh

I also suspect this missing dependency to be the source of some issues I saw on forums about openbazaar not being able to open some obscure files..

**Comment by Jchase2** [comment]
Ok, this still appears to be a problem, my bad. 
Here's output from a fresh Ubuntu VM: http://pastebin.com/nDqviwy0

Not sure if that actually causes problems or not elsewhere. If zmq is just being used for obleisk I kind of doubt using the python extention would be problematic, but maybe we should pass:
 
    --zmq=bundled

To avoid running unnecessary tests, assuming having system bindings isn't necessary.

**Comment by Jchase2** [comment]
Ok, this may still be a problem, my bad. 
Here's output from a fresh Ubuntu VM: http://pastebin.com/nDqviwy0

Not sure if that actually causes problems or not elsewhere. If zmq is just being used for obleisk I kind of doubt using the python extension would be problematic, but maybe we should pass:
 
    --zmq=bundled

To avoid running unnecessary tests, assuming having system bindings isn't necessary.
