### ISSUE TITLE
configure.sh : python-zmq versus pyzmq

### ISSUE THREAD

**Issue by enjoyaol** [OpenBazaar/OpenBazaar#1050]
Why is the configure script containing, for the ubuntu section, two references to pyzmq ?

First one is installed using apt-get : this is python-zmq

Second one is installed using pip : pyzmq, from requirements.txt

I guess one or the other should be removed, or if both are used for any reason, maybe it would be nice from a code maintainance PoV to use only one system for that ?

**Comment by Jchase2** [comment]
@Renelvon 

I'd say this and #1049 can both be closed since zmq is no longer used. In configure.sh fedora still installs it, but I don't think that's pertinent to either issue.

**Comment by hoffmabc** [comment]
ZeroMQ is still required I believe due to Obelisk requirements.

**Comment by Jchase2** [comment]
@hoffmabc 

Ah, yeah. I guess I should have installed the new version first, heh. Outside of virtualenv it doesn't look like any zmq instance is installed, though, right? Except on Fedora. So this issue (1050) should be good.

As far as I can tell zmq is implemented (almost) exclusively by pip in /env now, but I'm not sure if Ubuntu still has trouble compiling without libzmq-dev on the system as noted in 1049. I know Slack used to complain about bindings, but doesn't anymore on this non-clean install. I'll be sure to do more testing after work tomorrow on a fresh ubuntu install and see. I'll update 1049 then. Not sure why it doesn't complain on slack anymore...
