### ISSUE TITLE
"Make me an arbiter/notary" reverts to unchecked on restart

### ISSUE THREAD

**Issue by netom** [OpenBazaar/OpenBazaar#1063]
What I do:

* I go the the "Settings" page by clicking "Settings" near the top right corner of the page.
* The basic store info page appears, ready to be edited.
* I click the "Arbiter" or "Notary" menu item in the left menu
* The arbiter/notary settings page appears.
* I click on "make me an arbiter/notary" label, or the checkbox next to it.
* The checkbox will appear checked.
* I click on the "Save" button
* A confirmation appears that the settings were saved.
* I can verify that I offer this servive by checking my store from a different test store
* I shut down, and then start the store again.
* I go to "Settings->Arbiter/Notary" page again.

What should be seen:
* I can see myself offering arbitration/notary service in the other shop
* The "make me arbiter/notary" checkbox is checked

What can be seen:
* I can see myself offering arbitration/notary service in the other shop
* The "make me arbiter/notary" checkbox is _NOT_ checked

**Comment by hoffmabc** [comment]
Fixed
