### ISSUE TITLE
Thoughts on architecture

### ISSUE THREAD

**Issue by rmull** [OpenBazaar/OpenBazaar#1080]
I think there could be much to gain by encapsulating some of the OpenBazaar features a little better. For example, one option would be as follows:

1. Contain the haggle protocol stuff inside a libhaggle library, a pyhaggle module, or both. The haggle protocol and Ricardian contracts are the meat and potatoes of the OB effort as far as I know.
2. Reuse an existing DHT or network implementation. I understand there is an effort underway to use libtorrent and I think that is the right idea. It is a poor use of resources to reimplement a DHT in every application that wants distributed networking. 
3. Separate out the interface stuff. It is a bit goofy to distribute local software that uses a web browser as an interface instead of using native windowing kits, and while that may be a good option for remotely-hosted OB instances, I do not think it is necessarily appropriate for local/native software.

I think that if the team focused its efforts into putting together and maintaining a bulletproof implementation of the haggle protocol with good documentation and bindings in popular languages, they wouldn't need to be spread thin trying to patch up a rickety handmade DHT, and wouldn't need to struggle with the web dev or UX stuff. A "reference client" is important, but until the modularity is achieved, it's going to be the only client.

It feels like the project rushed the publicity campaign and there's going to be a lot of pressure to fix UI and network bugs, and the modularity is going to fall by the wayside in order to make the software work well enough to handle an influx of non-developer users.

**Comment by hoffmabc** [comment]
#2 is currently being addressed and #3 is another area which we will begin addressing shortly. #1 is another challenge and one that @drwasho is heading up development on. I'm going to close this discussion for now because it's addressing multiple issues and there is no further discussion happening here. We should open another one around the Contracting Protocol though. I suggest @drwasho begin that process.

**Comment by drwasho** [comment]
Formalising the contract/trade protocol is definitely on the agenda. My new article on `OpenBazaar: The Platform` will make some big steps towards that, but it will be followed up by a more detailed description.
