### ISSUE TITLE
OB opens three browser tabs

### ISSUE THREAD

**Issue by Cabeceira** [OpenBazaar/OpenBazaar#1125]
I'm new to Openbazaar and i'm having an issue, please forgive my formatting since i'm new to github too.

I'm in OSX mavericks, using Safari as the default browser.
I installed OB.

If i run the command ./openbazaar start it opens a browser tab with 20+ connections, but when i check if my 12345 port is open (https://tools.bizarre.company/port-check/) i get "Connection Failed" and no one seems to read what type in chat.

If i run ./openbazaar -j -disable-stun-check --server-ip [my.ip] start it opens three browser tabs, with a different store in each tab. It seems that these three "stores" are only connected to each other (Here are print screens of the 3 tabs http://imgur.com/a/n6WqB ). And if i check the 12345 port i get successful connection.

Can someone help?

**Comment by BoBeR182** [comment]
Seems similar to bug #1198

**Comment by hoffmabc** [comment]
@Cabeceira are you sure you're not running OpenBazaar in development mode? You might be typing some argument that gives you dev mode. That's the only reason I'd see multiple browsers open up unless it's past runs still going. Please ensure that you've killed all openbazaar instances before starting it up again and see if you get multiple browsers launching. I'm closing this for now. Re-open if that doesn't solve it.
