### ISSUE TITLE
configure.sh asks for root

### ISSUE THREAD

**Issue by chatcannon** [OpenBazaar/OpenBazaar#1131]
Maybe I'm the only one who has a problem with this. If so, please ignore me. However, I expect there are some other people who do a double-take when a configure script starts asking for their root password.

I appreciate it that you're trying to make it easy for users to get the software up and running, but I think that anyone who is checking out beta quality software from Github is probably also competent enough to read a README or INSTALL file and run the appropriate package manager themselves (especially if you provide easily copy-pasted commands for each OS).

If you're not dead-set against this I would be happy to make the necessary changes (including writing an INSTALL file etc) in a pull request for you to review.

**Comment by amingilani** [comment]
Seeing that this has been up for months without the devs opposing it, go for it!

+1 as long as you don't make the install process complicated

**Comment by jamesdwilson** [comment]
Ran into this also on Ubuntu/Mint 3.8 / x64

Thank you!

**Comment by acrisci** [comment]
The configure script is using the system package manager to install packages which requires root. I think this is a bad idea.

Instead, it should check if the system has each dependency installed, and if it doesn't, it should exit with an error and tell the user what needs to be installed.

I think it would also be acceptable to simply list the required dependencies in the installation documentation.

**Comment by jamesdwilson** [comment]
echo out the line that we are currently calling directly (sudo install
xyz), and let the user copy /paste it?

**Comment by acrisci** [comment]
@jamesdwilson, that is ambitious because then you have to support every package manager.

It's better to use things like pkg-config and python-specific things like setuputils. There are likely other good solutions out there for this sort of thing as well. Building and distributing python modules is a common use case.

**Comment by jamesdwilson** [comment]
Well already it is doing the install line. I am just suggesting echoing it
out to the user to help them along and not running it.

You're suggesting removing the install line entirely?


Thank you!

**Comment by lucayepa** [comment]
Agree to echo to the user what to do as root. Installing anything with superuser login is ridiculous and should be avoided.

**Comment by hoffmabc** [comment]
Addressed in #1274
