### ISSUE TITLE
Use Testnet checkbox (Settings > Advanced)

### ISSUE THREAD

**Issue by Klakurka** [OpenBazaar/OpenBazaar#1139]
I was going through the settings pages and noticed that the "Use Testnet" checkbox does not apply.

The checkbox value (settings.testnet) is getting passed back correctly but settings.testnet is blank on page refresh. The Obelisk textbox is being saved as expected.

I'm in here revising some of the GUI components -- could anyone point me in the right direction regarding where these settings values go to be saved?

We're sending the values out in settings.js (line 201; Connection.send('update_settings', query);), but it's unclear to me where that message is actually going.

![advancedcb](https://cloud.githubusercontent.com/assets/4713204/5521295/478a31b4-8951-11e4-84fe-37d070e8c64c.png)

**Comment by hoffmabc** [comment]
This was removed in the latest version and we may revisit Test Network compatibility at a later date.
