### ISSUE TITLE
Encountered a problem with GPG: Expected string type, got <type 'NoneType'>

### ISSUE THREAD

**Issue by acidsploit** [OpenBazaar/OpenBazaar#1143]
Hi,

I can not get OpenBazaar to run. It crashed after the following error:
Encountered a problem with GPG: Expected string type, got <type 'NoneType'>

I'm running Arch Linux and have all dependencies installed AFAIK. I've tried it on 2 machines, and did 3 clean OpenBazaar installations on both machines, always with the same result.

REPRODUCTION
----------------------------------------------------------------------------
[ thomas@thinkpad ~/build ] $ git clone https://github.com/OpenBazaar/OpenBazaar.git
Cloning into 'OpenBazaar'...
remote: Counting objects: 13432, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 13432 (delta 8), reused 0 (delta 0)
Receiving objects: 100% (13432/13432), 16.84 MiB | 3.15 MiB/s, done.
Resolving deltas: 100% (8402/8402), done.
Checking connectivity... done.
[ thomas@thinkpad ~/build ] $ cd OpenBazaar/

[ thomas@thinkpad ~/build/OpenBazaar ] $ ./configure.sh

.
.
.

[ thomas@thinkpad ~/build/OpenBazaar ] $ ./openbazaar start; tail -f logs/production.log
tail: cannot open ‘logs/production.log’ for reading: No such file or directory
tail: no files remaining
[ thomas@thinkpad ~/build/OpenBazaar ] $ Checking NAT Status...
{'nat_type': 'Symmetric NAT', 'external_ip': '83.134.xxx.xxx', 'external_port': 1031}
[openbazaar] bootstrapping database  ob.db
Created database file
[openbazaar] database setup completed

Generating PGP keypair. This may take several minutes...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/thomas/build/OpenBazaar/env/lib/python2.7/site-packages/gnupg.py", line 741, in _read_response
    result.handle_status(keyword, value)
  File "/home/thomas/build/OpenBazaar/env/lib/python2.7/site-packages/gnupg.py", line 542, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'PINENTRY_LAUNCHED'

Encountered a problem with GPG: Expected string type, got <type 'NoneType'>
[ thomas@thinkpad ~/build/OpenBazaar ] $ 

[ thomas@thinkpad ~/build/OpenBazaar ] $ sudo ./openbazaar start; tail -f logs/production.log
Checking NAT Status...
{'nat_type': 'Symmetric NAT', 'external_ip': '83.134.xxx.xxx', 'external_port': 1031}
Generating PGP keypair. This may take several minutes...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/thomas/build/OpenBazaar/env/lib/python2.7/site-packages/gnupg.py", line 741, in _read_response
    result.handle_status(keyword, value)
  File "/home/thomas/build/OpenBazaar/env/lib/python2.7/site-packages/gnupg.py", line 542, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'ERROR'

Encountered a problem with GPG: Expected string type, got <type 'NoneType'>

**Comment by Ulvhedin** [comment]
any update?

**Comment by hoffmabc** [comment]
Question… @Ulvhedin. I was under the impression that gpg would only leverage version 2.x if you used the gpg2 command. No matter if I install 2.1.1 or not my OpenBazaar always leverages the 1.4.x branch using the gpg command. What have you done to ensure that it always uses gpg2? Did you make gpg alias to gpg2? Or is this something that ArchLinux does?

**Comment by acidsploit** [comment]
@hoffmabc 
Thats bang on! And this would be something Arch does, I haven't touched the binaries or links.
```bash
xx@sabertooth ~> which gpg
/usr/bin/gpg
xx@sabertooth ~> ls -la /usr/bin/gpg
lrwxrwxrwx 1 root root 4 Dec 16 20:39 /usr/bin/gpg -> gpg2*
xx@sabertooth ~> 
```

**Comment by Ulvhedin** [comment]
OK. Workaround is to install gpg 1.4.18. It can be installed with gpg2. After installation just do following:
rm /usr/bin/gpg
ln -s /usr/bin/gpg1 /usr/bin/gpg
I just checked and it's working fine.

But.. this is only workaround :(

**Comment by hoffmabc** [comment]
I can try and get it working to support 2.x but it's not high priority for me right now.

**Comment by acrisci** [comment]
I'm getting this error as well.

**Comment by acrisci** [comment]
python-gnupg is not compatible with gpg version 2. I've opened a pull request [here](https://bitbucket.org/vinay.sajip/python-gnupg/pull-request/9/added-handling-for-pinentry_launched/diff) on the project to propose a way to fix this.

Now the `passcode` given when the key is generated is ignored and a dialog is launched that asks for a password. There is no way to generate a key without prompting for user input to enter the password, so this step should be documented as part of the configuration process.

This issue can be closed because the bug is somewhere else.

**Comment by M0Rf30** [comment]
fixed with latest python2-gnupg commits

**Comment by jebriggsy** [comment]
Exactly what permissions are required for key generation?  I'm having a similar issue on my Gentoo machine.   My ~/.gnupg folder and all files in it have 0600.  I am running openbazaar as myself so owner read/write should be fine, right?

```
Generating PGP keypair. This may take several minutes...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/***/OpenBazaar/env/lib/python2.7/site-packages/gnupg.py", line 753, in _read_response
    result.handle_status(keyword, value)
  File "/home/***/OpenBazaar/env/lib/python2.7/site-packages/gnupg.py", line 557, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'ERROR'
Encountered a problem with GPG: execv() arg 2 must contain only strings
```

This is with most recent commit 77fdaca8b9c5c6e66e2a053bc31fdf024401b275

Relevant versions:
gnupg 2.0.26
libgcrypt 1.5.4
python_gnupg 0.3.7

**Comment by M0Rf30** [comment]
you have to use python gnupg mercurial commit

**Comment by jebriggsy** [comment]
I'm assuming [this](https://bitbucket.org/vinay.sajip/python-gnupg/commits/76eede4cdffd647e07918a2fecee9ece74d114fe) is the commit you are referring to?

**Comment by jebriggsy** [comment]
After checking debug logs it seems that the GNOME keyring manager was interfering with key generation.

```
sudo killall gnome-keyring-daemon
./openbazaar start
```

Fixed the problem.  Users should be advised to configure their gnome-keyring to not manage gpg.

**Comment by hoffmabc** [comment]
OK Great. I will close this issue.
