### ISSUE TITLE
Inactive hosts not getting removed from DHT, getting spammed with TCP SYN

### ISSUE THREAD

**Issue by rmull** [OpenBazaar/OpenBazaar#1150]
My node has been offline for a long time (2 weeks, maybe more). I have a somewhat high volume of incoming TCP connection requests to my IP address, and all of them get a TCP RST response from me. The volume is often multiple SYN packets per second from ~30 unique addresses since I last checked.

How can I get my address removed from the DHT? Is there some packet I can respond with that will do it? I would think that issuing RSTs would indicate my node's desire to not participate in the DHT. What is recommended?

Thanks

**Comment by SamPatt** [comment]
Sorry this is happening. @hoffmabc, any thoughts on this?

**Comment by hoffmabc** [comment]
I'm not sure there is a good way to just make it stop at the moment unless we can get all the nodes to flush their systems. I will certainly flush the seed servers to get you out of there and see if it helps since other new nodes would get you as a peer from them.

**Comment by rmull** [comment]
Thanks, that should at least prevent it from getting worse. I glanced through the code and I didn't see where nodes get dropped from the DHT. What are the conditions under which nodes get removed? I was originally thinking I could maybe trigger those conditions by sending broken packets or something but like I said I couldn't make out exactly how it works.

**Comment by hoffmabc** [comment]
@rmull is this still an issue? Most nodes should not be using or sending TCP packets any longer. I want to close this issue.

**Comment by rmull** [comment]
Looks like all is now quiet and this issue can be closed. Thank you for following up! I'll leave a tcpdump running for a few hours to see if there are any hosts out there running the old TCP OB stores for curiosity's sake.
