### ISSUE TITLE
First time setup walkthrough in GUI

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#117]
It would probably be valuable to have a first time setup in the GUI when the user starts OB initially. Ask if they want to use Bitmessage, if they want to use the highest rated notaries automatically, explain how OB is different than other platforms, etc. Or perhaps we can direct them to a YT video with tutorial?

It could ask if the user wants to set up a store to sell, or they only want to buy. If they want to set up a store it can walk them through setting up a simple contract.

I'm sure there will be plenty other things that we'll think of later that would be useful to inform a first time user of, and get their information in upfront.

**Comment by drwasho** [comment]
So @SamPatt did this for our beta 4.0 release, so yay, we can close this.

@ChangeTip, send a warm fuzzy feeling to @SamPatt

**Comment by changetip** [comment]
Hi @sampatt, I've delivered a Bitcoin tip worth a warm fuzzy feeling from @drwasho to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
