### ISSUE TITLE
Client allows invalid Bitcoin address to be entered for payment

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1170]
When the seller puts in their Bitcoin address and marks the product as shipped, there is no check to ensure it is a legitimate Bitcoin address. I put "test" in the field and it didn't stop me. We'll need a check there to prevent user error.

**Comment by dionyziz** [comment]
@pkakelas can take this

**Comment by rippler** [comment]
Perhaps could be added these planned enhancements for overall input validation (https://github.com/OpenBazaar/OpenBazaar/issues/836).

**Comment by hoffmabc** [comment]
@pkakelas @rippler I submitted a very naive PR on this one. It's not truly validating the BTC address as valid, but checking for format (i.e. right characters and length of string). This should be superseded at some point by something that does the proper math validation on the address.
