### ISSUE TITLE
"openbazaar start" stuck at Generating PGP keypair

### ISSUE THREAD

**Issue by tech-no-crat** [OpenBazaar/OpenBazaar#1189]
Hello,

I am trying to run OpenBazaar on a Ubuntu 14.04.1 LTS machine. After running `configure`, which gave a few warnings which seemed unimportant, `openbazaar start` gets stuck. `logs/production.log` is empty. I've tried waiting more than 10 minutes twice and nothing happens, the server is unreachable at port 52358.

```
root@mazonakis:~/OpenBazaar# ./openbazaar start;
root@mazonakis:~/OpenBazaar# Checking NAT Status...
{'nat_type': 'Full Cone', 'external_ip': '<myip>', 'external_port': 52358}
Generating PGP keypair. This may take several minutes...
```

**Comment by SamPatt** [comment]
On a virtual machine you need more entropy to generate the keys. Try installing haveged:

    sudo apt-get install haveged

Then try it again, it should only take a few seconds.

**Comment by tech-no-crat** [comment]
It worked, thank you :)

**Comment by dionyziz** [comment]
Should we add this as a dependency? Or at least show a message saying "if it takes too long try x"
