### ISSUE TITLE
Changing store name causes duplication of connected markets

### ISSUE THREAD

**Issue by johndevor** [OpenBazaar/OpenBazaar#1194]
Changing the name of my store causes a duplication of a connected store's node:

Not sure on what level this needs to be filtered (just a gui bug or deeper)?

![screen shot on 2015-03-02 at 12-55-27](https://cloud.githubusercontent.com/assets/75827/6446797/75bb74fa-c0db-11e4-8ed6-2eb80f48b77a.png)

**Comment by hoffmabc** [comment]
This is fixed in a later code. I recommend you pull this code if you are going to rigorously test. https://github.com/hoffmabc/OpenBazaar/commits/feature-0.4-fixes

**Comment by hoffmabc** [comment]
This is

**Comment by johndevor** [comment]
Got it will do thanks.
