### ISSUE TITLE
Not just selling items on OpenBazaar - Also include "I would like to buy items/services of this and that sort"

### ISSUE THREAD

**Issue by kallevedin** [OpenBazaar/OpenBazaar#1195]
It is possible to sell items on OpenBazaar, by adding items one wish to sell to ones shop.

It could also be possible to list items that one would like to buy. For example, a shop could include a list of "stuff or services i would like to buy", together with the price one would be comfortable with paying for such a thing/service.

Idea: Two separate lists (web pages), one for selling stuff, one for buying them.

**Comment by theblacksquid** [comment]
Thats an "invitation to tender", and yes, it will be part of  the overall system, and critical for our implementation of a Decentralized Exchange

**Comment by rippler** [comment]
I like this!

**Comment by drwasho** [comment]
Invitation to Tender is super important, a big feature I personally can't wait for. But it will be for all goods and services. We have a lot of more fundamental things to build first.

**Comment by theblacksquid** [comment]
:+1: :
