### ISSUE TITLE
Don't run apt-get update in scripts

### ISSUE THREAD

**Issue by abderraouf-adjal** [OpenBazaar/OpenBazaar#1201]
Hi,
I'm suggesting to not run `sudo apt-get update` in OpenBazaar configuration or install scripts.

It's better to let the user do it manually, And print RED warning without exit if the last time `apt-get update`  was performed is +3 days.

I recommend [getLastAptGetUpdate()](https://github.com/gdbtek/ubuntu-cookbooks/blob/master/libraries/util.bash#L283) to do the job.

**Comment by sophron** [comment]
There was a similar issue (#517) some months ago regarding `apt-get upgrade`.

`apt-get update` is considered safe and i don't see any problem with it. it's true that the machine may enter a state without the administrator being aware of that, so a warning that this command will be executed may be useful.

**Comment by jamesdwilson** [comment]
I agree none of our scripts should run sudo, only should suggest running
sudo <Commandname> and let the user do it.
Because of the very sensitive nature of our app, I think this is a must.

On Thu, Mar 19, 2015 at 9:00 PM, George Chatzisofroniou <
notifications@github.com> wrote:

> There was a similar issue (#517
> <https://github.com/OpenBazaar/OpenBazaar/issues/517>) some months ago
> regarding apt-get upgrade.
>
> apt-get update is considered safe and i don't see any problem with it.
> it's true that the machine may enter a state without the administrator
> being aware of that, so a warning that this command will be executed may be
> useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBazaar/OpenBazaar/issues/1201#issuecomment-83850624>
> .
>



-- 
Thank you!

**Comment by abderraouf-adjal** [comment]
Who will use a software like OpenBazaar is knew what to do, He don't need `apt-get update` in installation script to check for him.

**Comment by hoffmabc** [comment]
We now have a warning message and prompt. I'm closing this. Please re-open if you feel there is still more to discuss @abderraouf-adjal or @jamesdwilson
