### ISSUE TITLE
Remove removes contract before confirmation, Undo can't undo that

### ISSUE THREAD

**Issue by rippler** [OpenBazaar/OpenBazaar#1209]
As Subject.
When I click on Remove, the contract disappears just as "Are you sure..." starts appearing.
Then when I click on Undo, nothing happens.

OS: Win 8.1 x86 with OB binary

**Comment by hoffmabc** [comment]
Is this the latest develop code?

**Comment by rippler** [comment]
It's the binary download for Windows available here, but it's not labeled in such a way that it's possible to tell which build or sub-version it is...

**Comment by hoffmabc** [comment]
Ok this is a bug and is fixed by the PR referenced in this ticket.
