### ISSUE TITLE
Contract Viewing (modal) and Exporting

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#122]
Seed contracts listed by users or within a seller's shop-front should be viewable after they have been posted. That is to say that when we click on them, a modal should popup with the details of the contract WITH an option to export the contract... after all, we do have the option to import a contract.

**Comment by SamPatt** [comment]
This is completed except I don't think we have a specific export function. @hoffmabc, is this an easy task? I can ask for volunteers on Slack to tackle this.

**Comment by hoffmabc** [comment]
Break this into a separate issue for export.
