### ISSUE TITLE
--seeds argument not in --help

### ISSUE THREAD

**Issue by jordonias** [OpenBazaar/OpenBazaar#1220]
No details on how to use ``--seeds`` argument is documented in ``--help``.

https://github.com/OpenBazaar/OpenBazaar/blob/develop/node/openbazaar.py#L84

**Comment by hoffmabc** [comment]
ok @jordonias there's a PR in for this fix. 

You basically would specify your seed nodes by saying
``` 
./openbazaar -s 127.0.0.1:12345 127.0.0.1:12346 start 
```
