### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by M0Rf30** [OpenBazaar/OpenBazaar#1223]
If I create a contract, the form asks for a price in dollars for the product and in bitcoin for the shipping.
Under the contracts menu, a table show me 2 prices in bitcoin

**Comment by hoffmabc** [comment]
There should be no place in the UI that asks for prices in Dollars. Can you take a screenshot of where you are finding this?

**Comment by M0Rf30** [comment]
![screenshot from 2015-04-16 14-18-29](https://cloud.githubusercontent.com/assets/491117/7180674/348c0b3e-e444-11e4-9fac-29f1512f8fdb.png)
![screenshot from 2015-04-16 14-18-44](https://cloud.githubusercontent.com/assets/491117/7180673/348b0540-e444-11e4-8f7b-cbd632a2b16c.png)

**Comment by M0Rf30** [comment]
latest commit of devel branch

**Comment by hoffmabc** [comment]
Ok that's maybe a bad UI choice. It's not asking for the price in USD, it's telling you how much it would be in USD. Sorry for the confusion.

**Comment by M0Rf30** [comment]
It's a pleasure :+1:

**Comment by hoffmabc** [comment]
I'm going to close this and probably change the way that is viewed. Thanks.
