### ISSUE TITLE
404 error log

### ISSUE THREAD

**Issue by M0Rf30** [OpenBazaar/OpenBazaar#1224]
tornado.access - WARNING - 404 GET /html/%7B%7Bmyself.settings.avatar_url%7D%7D (127.0.0.1) 1.22ms
tornado.access - WARNING - 404 GET /html/%7B%7Bpeer.avatar_url%7D%7D (127.0.0.1) 1.22ms
tornado.access - WARNING - 404 GET /html/%7B%7Bshout.avatar_url%7D%7D (127.0.0.1) 1.21ms

**Comment by hoffmabc** [comment]
Ok we need to add ng- prefixes on img srcs or Angular will load this after the page is already rendered and these messages will show. Will fix.
