### ISSUE TITLE
Node died on 0.4; List size changed during iteration

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1231]
I don't believe I was doing anything when this happened.

````openbazaar::start_io_loop Exception: list changed size during iteration
Process Process::openbazaar_daemon::target(start_node):
Traceback (most recent call last):
 File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
   self.run()
 File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
   self._target(*self._args, **self._kwargs)
 File "node/openbazaar_daemon.py", line 397, in start_node
   start_io_loop()
 File "node/openbazaar_daemon.py", line 329, in start_io_loop
   tornado.ioloop.IOLoop.instance().start()
 File "/root/OpenBazaar/env/local/lib/python2.7/site-packages/tornado/ioloop.py", line 768, in start
   due_timeouts.append(heapq.heappop(self._timeouts))
RuntimeError: list changed size during iteration````

**Comment by hoffmabc** [comment]
Make sure to report OS as well. Thanks.

**Comment by SamPatt** [comment]
Right. Ubuntu 14.04.

**Comment by zariok** [comment]
I received the same error. Ubuntu 14.04, it happened after I clicked "Republish" on the contract page.

**Comment by drwasho** [comment]
The republish button issue us a known bug, patch should be out soon.

**Comment by zariok** [comment]
Just received after a contract edit -> (keyword) -> save

**Comment by hoffmabc** [comment]
It seems as though possibly there are a massive amount of timeout objects queuing up in the tornado ioloop causing this. Trying to work through alternative ways of dealing with this so they don't get backed up.

**Comment by Ruxton** [comment]
Just received when doing absolutely nothing.

OS: Ubuntu 14.04
OB Version: 0.4
Python 2.7.6
