### ISSUE TITLE
Edit Contract doesn't retain keywords

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1232]
When using the edit contract feature, the existing keywords are eliminated.

**Comment by gubatron** [comment]
can't replicate here.

I add comma separated list of keywords, then edit contract, keywords still there, change keywords, new keywords are there.

perhaps something special about the keywords being used.

Could you be more detailed in the steps to reproduce this issue? (or perhaps it was already fixed and this ticket remains open)
