### ISSUE TITLE
Endless page refresh loop after clicking a store.  Mac 10.10.3, safari and chrome.

### ISSUE THREAD

**Issue by Idealist42** [OpenBazaar/OpenBazaar#1233]
After clicking on peer, the page goes into an auto-refresh mode where it's almost as if the refresh button is being clicked a couple times per second.

I get this http://pastebin.com/2KhqaC7M over and over again in my browser console while it's auto refreshing.

This is with a clean install of openBazaar.  Deleting the database and running configure again didn't help.

**Comment by SamPatt** [comment]
Does this happen with any peer or only the 'seed0' or 'seed1' peers?

**Comment by Idealist42** [comment]
So far just the seed0/1 peers.  I haven't seen any other peers yet.  I've been fighting with upnp.  How can I start openbazaar with upnp disabled, and on a specific port that i have manually forwarded?

**Comment by SamPatt** [comment]
Use ````./openbazaar help```` to find the arguments you need.

Sounds like probably ````./openbazaar -j -p [port] start````

Also try running ```` killall python -9```` to make sure all processes are cleared.

**Comment by Idealist42** [comment]
Thanks.  Running

./openbazaar --disable-stun-check -j --server-ip [myIP] --server-port 34205 start

seems to do the trick...  I see a python process listening on udp 34205 now.
  
But I still don't see any other peers, and the looping bug is still present.

I tried killall python -9.  There was nothing to kill.

**Comment by pellicceama** [comment]
This is happening to me as well. Your command @Idealist42 doesn't seem to fix the issue for me. All python processes are also dead. Happening on OS X 10.9.5, Chrome, FF and Safari.
