### ISSUE TITLE
Price input is unclear and confusing users

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#1239]
The price input section in contracts shows a dollar sign in order to help convert, but it makes uses think they are inputting the price in USD.

![priceob](https://cloud.githubusercontent.com/assets/6955773/7284034/b29b5250-e908-11e4-8689-8af0ec82dea7.png)

 I've already seen multiple examples of users putting the price in USD instead of Bitcoin. The interface should be changed to make it more clear the price is set in Bitcoin, and the USD is only there as a conversion tool.

**Comment by ulrichard** [comment]
Once the converted dollar value apers, it becomes clear. But as long as there is only the dollar sign and USD, it's confusing.

**Comment by amingilani** [comment]
Maybe add a `BTC` to the right of the input field? Or a `฿` to the right?

**Comment by SamiLehtinen** [comment]
I thought during the beta that the USD reference was really confusing. But I believed it would get fixed before release.

**Comment by amingilani** [comment]
Maybe `1337 BTC` as placeholder text? Although, personally, I prefer `BTC` on the right.

**Comment by GortMcTabs** [comment]
What about a ```≈ $nn.nn``` appearing right of the input text field once a value is entered? This way it looks more like an actual equation. Putting ```BTC``` right justified in the input text field should cut down on the confusion.

**Comment by drwasho** [comment]
@taravancil can you take a look at this and propose a fix, we can possibly flag this as a 0.4 patch.

**Comment by taravancil** [comment]
Yeah, I can see how this would confuse users! I propose removing the dollar sign and placing a `BTC` label to the right of the input field.

**Comment by hoffmabc** [comment]
How does this look?

![image](https://cloud.githubusercontent.com/assets/45482/7337374/58a79dfe-ebf5-11e4-9b25-b5c1ee1359c0.png)

**Comment by drwasho** [comment]
Sold to the man with the thing...
