### ISSUE TITLE
# of markets & CPU time consumption

### ISSUE THREAD

**Issue by SamiLehtinen** [OpenBazaar/OpenBazaar#1245]
It seems that when client is running for several hours, it's using more and more memory and CPU cycles and number of peers it reports seems to be constantly growing. If network grows at all, this will become intolerable, it's bad enough already. Client might report 183 markets and after restart it's under 40. CPU time consumption doesn't even grow linearly it seems to be growing exponentially. That's bad.

**Comment by hoffmabc** [comment]
I'm going to most likely submit a PR soon that would be interesting to see if you could analyze the same way.

**Comment by hoffmabc** [comment]
Addressed in last commits.
