### ISSUE TITLE
Link to Git for Windows is missing in Wiki

### ISSUE THREAD

**Issue by rippler** [OpenBazaar/OpenBazaar#1250]
http://git-scm.com/download/win should be added behind [here] in https://github.com/OpenBazaar/OpenBazaar/wiki/Windows-support#requirements
Also maybe add https://technet.microsoft.com/en-us/library/ee176961.aspx to the PowerShell related part.

**Comment by SamPatt** [comment]
Thanks Rippler. Changes made.
