### ISSUE TITLE
Bugs with messages

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar#1251]
I've just encountered two bugs with messages:

First, I received a message, but the name of the sender did not appear (neither in the inbox, nor when clicking on the message). It was only AFTER I responded to the message the name of the sender appeared.

Second, when responding to the message, I was given three possible options for the destination: A blank line (which worked), and two others that I can't remember (seed node, or something like that). Now that I have responded to this first message, when I a try to send a new message, all of a sudden, a million addresses appear.

Both of these problems appear to be related to a first time setup issue. Now that I have sent my first message, everything now appears to be working.

**Comment by drwasho** [comment]
Part of the reason for this behaviour is due to the nature of the messaging service, which only functions when nodes are online.

**Comment by lunokhod** [comment]
After OpenBazaar crashed and I restarted, this problem reappeared: The name of the sender of the message does not appear in the message box (see image below).

![screen shot 2015-04-26 at 09 35 55](https://cloud.githubusercontent.com/assets/8471949/7336314/556c8d4a-ebf8-11e4-8b80-58625265dca3.png)

Also, if I try to send a message to a user that is online, this is what the message box looks like:
![screen shot 2015-04-26 at 09 42 04](https://cloud.githubusercontent.com/assets/8471949/7336318/91776a80-ebf8-11e4-9609-3d2e9ea2b6ca.png)

The username does not appear, and their are only two allowable addresses to choose from.

**Comment by hoffmabc** [comment]
There are a slew of messaging bugs that we will try to stomp out for the next release. Thanks for reporting.

**Comment by gubatron** [comment]
have you guys considered not reinventing the wheel for reliable messaging and giving users the option of using email, via https://docs.python.org/3/library/smtplib.html

**Comment by hoffmabc** [comment]
That's something I hope to incorporate so we can do email notifications but this is a good compromise in the meantime. The code was already written and leverages the existing p2p network. Also Bitmessage wasn't cutting it.

**Comment by gubatron** [comment]
so this would be more like a chat type of thing, gotcha.

**Comment by gubatron** [comment]
email seems necessary for both seller/buyers.

"[Store-Acme] You have 1 new order!"
"[Store-Acme] You have 1 new order!"
"[Store-Acme] You have 1 new order!"

Would be awesome being a seller and seeing that on your store's inbox

and then as a buyer

"[OpenBazaar Store-Acme] Your order has shipped"

**Comment by hoffmabc** [comment]
Yes it's not meant to be a full fledged email type replacement.

**Comment by gubatron** [comment]
the beauty of leveraging email, is that initially all email-messaging can be done with another email client, but eventually OB could have an interface to manage order related messaging. It could organize conversations by tagging emails with order-related data.

**Comment by yagoulas** [comment]
@gubatron: I think that using email could easily reveal the identity of a user. Exchanging messages between peers in a completely encrypted manner like we do sounds much safer.

**Comment by gubatron** [comment]
if you want to build openbazaar for drug dealers sure, and still, it's not that hard to create an anonymous email, while connected behind several VPN proxies paid for with Bitcoin through a wallet that was connected via TOR.... 

I'm thinking about the 99% of people out there that need to buy and sell regular goods.

**Comment by hoffmabc** [comment]
Find me 99% of the general population that will input their mail server information including SMTP server and authentication. The illegal goods argument is bullshit and we shouldn't argue about privacy. It's necessary and that's a distraction from the issue at hand which is users need an easy secure way to communicate.

**Comment by gubatron** [comment]
ever heard of Outlook, Thunderbird, Mail... millions of users at some point had to setup an email account.

We could make it automatical so that they don't have to put anything but their email and password if you detect common email services like gmail, hotmail, yahoo, etc.

**Comment by hoffmabc** [comment]
I'm not saying it's not needed but you were talking about reinventing the wheel. We already have a button where you can email someone. Let's not conflate illegal activity though with this. I think it can make sense for some cases but not for all messaging.

**Comment by gubatron** [comment]
yes, that's what I meant by the new "Email Me" button. That should help somewhat for now.

**Comment by yagoulas** [comment]
Wait, aren't we reinventing the wheel anyway? Ebay already does most of what OpenBazaar tries to achieve.

**Comment by gubatron** [comment]
we're making a slightly different wheel, some existing parts may be reused, like email.

**Comment by yagoulas** [comment]
That doesn't make sense. We could alright try to use existing wheels like VISA  or Mastercard for online payments.

**Comment by gubatron** [comment]
I think you should.

**Comment by hoffmabc** [comment]
I opened two separate tickets for these bugs #1291 and #1292. I will close this issue.
