### ISSUE TITLE
Preview images from URL during contract creation

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#1259]
Add some code to make a live preview of the image URL in the contract creation modal. This will allow users to quickly see if image/URL is valid.

I've already got code for this, I'll submit the PR later today.

**Comment by hoffmabc** [comment]
That's dangerous

**Comment by drwasho** [comment]
How so?

**Comment by hoffmabc** [comment]
You coding.

**Comment by drwasho** [comment]
Hahaha... screw you.

**Comment by theblacksquid** [comment]
:+1: 
These things make me wish I could get on Slack while at work.

**Comment by rippler** [comment]
Are the pics pulled directly from the URLs? 
Hopefully at the same time a "Don't load external HTTP images" (i.e. anything that's not `localhost`) setting could be added to avoid easy (potential) buyer identification via the IP address.
