### ISSUE TITLE
Notary payment

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#126]
Notaries sign transactions and create multisig, but what is their incentive for doing this? I know we've mentioned that they would get paid for this, but I don't think we've fleshed out exactly how that occurs. Is it for every transaction, or only certain ones? Do we put a payment option in the GUI, or make it automatic, or do they have to arrange a new contract first? 

I'm asking because we need to think through how they are incentivized to operate, and if this requires being coded into the client or not.

**Comment by hoffmabc** [comment]
We've already built this in as a % of sale if they intervene. Tipping could be separate.
