### ISSUE TITLE
Cannot add GUID successfully on OS X 10.10

### ISSUE THREAD

**Issue by charlesfries** [OpenBazaar/OpenBazaar#1261]
Add GUID, OB says "GUID valid," but the GUID does not remain in the sidebar

**Comment by hoffmabc** [comment]
There is a description in the UI that explains that adding GUIDs does not guarantee a connection nor does it mean it will stay in the sidebar. It merely will go out and search other nodes for connection info to find that GUID. If it's not accessible then it will not be able to add it to your sidebar as an available market. Hope that helps!
