### ISSUE TITLE
-p for p2p configuration doesn't work

### ISSUE THREAD

**Issue by elroman0** [OpenBazaar/OpenBazaar#1267]
-p for p2p configuration doesn't work

Nikit4:OpenBazaar administrateur$ ./openbazaar start -p 59302
Nikit4:OpenBazaar administrateur$ Checking NAT Status...
{'nat_type': 'Full Cone', 'external_ip': '178.82.230.104', 'external_port': 53814}
Setting up UPnP Port Map Entry...
UPnP TCP P2P Port Map configuration done  (53814 -> 53814) => False
UPnP UDP P2P Port Map configuration done  (53814 -> 53814) => False
Warning: UPnP was not setup correctly.  Ports could not be automatically mapped.
If you only see two or three stores, here are some tips:
1. If you are using VPN, configure port forwarding or disable your VPN temporarily
2. Configure your router to forward traffic from port 53814 for both TCP and UDP to your local port 53814
Started OpenBazaar Web App at http://127.0.0.1:54681

**Comment by SamiLehtinen** [comment]
Surely it does. You might need to configure -j and --disable-stun-check with it.

**Comment by hoffmabc** [comment]
Yes that might be kind of confusing but the uPnP and STUN checks will auto-assign ports overriding your specific -p setting. I'll close this and if you are still seeing an issue we can reopen it.
