### ISSUE TITLE
Product descriptions don't preserve new lines

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#1268]

**Comment by STRML** [comment]
Probably just needs "white-space: pre-wrap" in the css.

**Comment by hoffmabc** [comment]
Where are you seeing this @dionyziz? I thought we just closed a PR related to this.
https://github.com/OpenBazaar/OpenBazaar/pull/1258

I think these bug reports need a more detailed description or screenshot. This one is pretty vague.

**Comment by gubatron** [comment]
works for me (opening my own contracts)
![screen shot 2015-05-02 at 8 19 40 pm](https://cloud.githubusercontent.com/assets/163977/7443221/ccca62ee-f108-11e4-9675-2fe98535a9a2.png)

**Comment by hoffmabc** [comment]
@dionyziz clarify or i'll close the bug. Not sure what this is.
