### ISSUE TITLE
Add "Contact Merchant"

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#129]
When viewing an item, there should be an option to contact the merchant so that buyers can ask questions about the product. 

When clicked, it should bring up the "Send Message" window from the Bitmessage tab, and filling the contract number in the subject line (if you can do that). This obviously only works if the merchant has publicly displayed their address. 

If the merchant doesn't have an address, we'll have to figure out another way (open up an email link if they chose email, or have another messaging system in client).

**Comment by drwasho** [comment]
Internal messaging and the ability to contact the merchant... done. More direct interactions can be raised in another issue.
