### ISSUE TITLE
Unique error after 'Generating PGP keypair' on Ubuntu 15.04

### ISSUE THREAD

**Issue by jdqx** [OpenBazaar/OpenBazaar#1318]
user@pc:~/git/OpenBazaar$ Checking NAT Status...
{'nattype': 'Full Cone', 'externalip': '108.201.65.149', 'external_port': 37517}
[openbazaar] bootstrapping database ob.db
Created database file
[openbazaar] database setup completed
Generating PGP keypair. This may take several minutes...
Process Process::openbazaardaemon::target(startnode):
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self.target(self._args, *self.kwargs)
File "node/openbazaardaemon.py", line 394, in startnode
application = MarketApplication(obctx)
File "node/openbazaardaemon.py", line 202, in _init__
self.transport = CryptoTransportLayer(obctx, dbconnection)
File "node/transport.py", line 125, in init
self.setupsettings()
File "node/transport.py", line 753, in setupsettings
self.generatenewkeypair()
File "node/transport.py", line 806, in _generatenewkeypair
signedpubkey = self.cryptor.sign(self.pubkey)
AttributeError: 'CryptoTransportLayer' object has no attribute 'cryptor'

**Comment by hoffmabc** [comment]
Which version of PGP do you have? Did you run ./configure.sh?

**Comment by hoffmabc** [comment]
More info @jdqx ?

**Comment by ahummel25** [comment]
Also getting this same error upon running ./openbazaar start. Any ideas?

**Comment by ahummel25** [comment]
I did run ./configure.sh. Not sure which version of PGP I have installed. Was that installed via config?

**Comment by hoffmabc** [comment]
Do you have the latest code? _generatenewkeypair is not even a current method name in the latest code. It shoudl be _generate_new_keypair. 
![screen shot 2015-06-01 at 12 37 49 pm](https://cloud.githubusercontent.com/assets/45482/7917824/1e1ca210-085b-11e5-8e50-1473bece042c.png)

**Comment by ahummel25** [comment]
Yes, I believe I do.

![image](https://cloud.githubusercontent.com/assets/12643871/7917880/22934b12-0853-11e5-9a7f-588c1c58153c.png)

**Comment by hoffmabc** [comment]
Ok do 
```
rm db/ob.db
./configure.sh
```

**Comment by ahummel25** [comment]
Ok I get passed that error, now it just sits at "Generating PGP keypair. This may take several minutes.."

I had gotten to this point before. I know this is a separate issue, but I had run into this before. Any workaround for this? I tried firing up http://localhost:<PORT> through browser but getting another error there too.

**Comment by hoffmabc** [comment]
ok remove the database again and install haveged:

```
rm db/ob.db
apt-get install haveged
./configure.sh
```

**Comment by ahummel25** [comment]
Did that, now I'm back to the same exact crypto error.

**Comment by rippler** [comment]
Prolly OS-related. Should retry on a 14.04 VM...

Possibly related: https://lists.launchpad.net/desktop-packages/msg116005.html

**Comment by ahummel25** [comment]
I'm running in Ubuntu 14.04.2.

**Comment by rippler** [comment]
Okay, in that case you may want to change the subject to make it easier on us:
> Unique error after 'Generating PGP keypair' on Ubuntu 15.04

**Comment by ahummel25** [comment]
Sorry, I did not create this issue. Just jumped in here when I saw the error message listed here. I might just try firing up a different Linux os.

**Comment by ahummel25** [comment]
Also trying it as root, same issue.

**Comment by ahummel25** [comment]
@rippler What OS have you gotten this to work on?

**Comment by jdqx** [comment]
OP here. Not sure how to get the PGP version number. 'pgp --version' did not work. Anyone know the proper command or need other info? Should I even continue trying OpenBazaar on Ubuntu 15.04? I'll get a 14.04 VM setup in the near future.

**Comment by hoffmabc** [comment]
@jdqx it's gpg --version

**Comment by rippler** [comment]
@ahummel25 I use Ubuntu 14.04 as the stable version, but I think others use newer clients as well. You don't need to try as root - you'll be prompted for `sudo` when it's time to install packages, but otherwise you can install and run as a non-root (sudoer) user. 
Don't try on Windows, as the installer (and/or binaries) for v0.4 isn't ready yet.

**Comment by ahummel25** [comment]
Now I'm running Ubuntu 14.04.1, same issues. Got past crypto error by rm-ing the ob.db, reran config, now sitting at Generating PGP keypair.

**Comment by ahummel25** [comment]
Here's my PGP version as well.

![image](https://cloud.githubusercontent.com/assets/12643871/7919197/416485de-085c-11e5-945b-8e9ed1b82c9e.png)

**Comment by rippler** [comment]
@ahummel25 did you start `haveged` service?

@hoffmabc I get the same error (`AttributeError: 'CryptoTransportLayer' object has no attribute 'cryptor'`) on a fresh Ubuntu 14.04 VM (with haveged installed and running).

**Comment by ahummel25** [comment]
I did not start haveged, I just installed it.

**Comment by hoffmabc** [comment]
Ok this is an error I introduced. Not sure why I wasn't reproducing it before, but will fix now.

**Comment by ahummel25** [comment]
@hoffmabc Thanks.

So will I need haveged running after this is fixed? How do I start that?
