### ISSUE TITLE
Wrong Wiki link

### ISSUE THREAD

**Issue by rippler** [OpenBazaar/OpenBazaar#1319]
On the first page there's a link to Getting Started
Now: 
https://github.com/OpenBazaar/OpenBazaar/wiki
Should be:
https://github.com/OpenBazaar/OpenBazaar/wiki/01.-Getting-Started

By the way, this isn't very convenient - it takes more to report a doc bug than to fix it.

**Comment by drwasho** [comment]
Got it, I'm working on the wiki this week. 

What do you mean by inconvenient?

**Comment by rippler** [comment]
I mean it would take me 30 seconds to fix the link compared to 2 mins to submit a bug, but it's okay - Github Wikis aren't easy to manage.

**Comment by drwasho** [comment]
Gotcha.

**Comment by drwasho** [comment]
Fixes to this and others are in the following PR: https://github.com/OpenBazaar/OpenBazaar/pull/1321

@hoffmabc anything else we need to change in the Readme?

**Comment by hoffmabc** [comment]
I pushed the PR since we will release tomorrow, but I will go back through for more thoughts on this.
