### ISSUE TITLE
Python errors after running ./openbazaar start

### ISSUE THREAD

**Issue by Jheguy2** [OpenBazaar/OpenBazaar#1339]
I've been getting this error on two different base installs of debian wheezy

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/OpenBazaar/node/openbazaar.py", line 14, in <module>
    import psutil
ImportError: No module named psutil
```

I'm guessing it's a dependency issue, any idea how to fix it?

**Comment by SamPatt** [comment]
This has been replicated across OSX and Ubuntu. Did you get any errors on running ./configure.sh?

**Comment by SamPatt** [comment]
@gubatron Do you know if this could be the configure script?

**Comment by rippler** [comment]
Can you try a non-obsolete Debian or Ubuntu?

Or can you install python-psutil manually (i.e. can it be built properly)? 
According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788504, it can't.

**Comment by Jheguy2** [comment]
configure.sh ran smoothly, except for these warnings

    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/gh-pages'
    warning: no previously-included files found matching 'bundled/zeromq/src/Makefile*'
    warning: no previously-included files found matching 'setup.cfg'
    warning: no previously-included files found matching 'zmq/libzmq*'
    warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
    warning: no previously-included files matching '.deps/*' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '.mailmap' found anywhere in distribution
    warning: no previously-included files matching 'Makefile.am' found anywhere in distribution
    warning: no previously-included files matching 'Makefile.in' found anywhere in distribution
  Running setup.py install for six

    no previously-included directories found matching 'documentation/_build'
  Running setup.py install for certifi

  Running setup.py install for backports.ssl-match-hostname

  Running setup.py install for zope.interface

    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution

but no errors to my knowledge, I'll go ahead and run it again on a clean VM and post the output

**Comment by gubatron** [comment]
@Jheguy2 can you do this for me from the openbazaar folder:

`./env/bin/pip show psutil`

and paste all the output here?

**Comment by Jheguy2** [comment]
./env/bin/pip show psutil
Usage: pip COMMAND [OPTIONS]

pip: error: No command by the name pip show
  (maybe you meant "pip install show")


Outdated pip?

**Comment by gubatron** [comment]
Maybe mine is outdated, I do get some output:

```
./env/bin/pip show psutil
You are using pip version 6.0.6, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---
Name: psutil
Version: 2.2.0
Location: /Users/gubatron/workspace.frostwire/OpenBazaar/env/lib/python2.7/site-packages
Requires: 
```

**Comment by gubatron** [comment]
upgrading...

**Comment by gubatron** [comment]
now, I get:

```
n$ ./env/bin/pip show psutil
---
Metadata-Version: 1.1
Name: psutil
Version: 2.2.0
Summary: psutil is a cross-platform library for retrieving information onrunning processes and system utilization (CPU, memory, disks, network)in Python.
Home-page: https://github.com/giampaolo/psutil
Author: Giampaolo Rodola
Author-email: g.rodola <at> gmail <dot> com
License: BSD
Location: /Users/gubatron/workspace.frostwire/OpenBazaar/env/lib/python2.7/site-packages
Requires: 
```

**Comment by gubatron** [comment]
so for sanity, make sure you have the latest pip. (`pip-7.0.3` is what I have now)

**Comment by Jheguy2** [comment]
My pip version:

 pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)


I'll go ahead and upgrade

**Comment by gubatron** [comment]
1.1!!! wow. Hopefully this is the reason for your issue.

**Comment by Jheguy2** [comment]
Just recreated the error in a clean Ubuntu 12.04 VM as well, maybe a problem with the pip version? Ubuntu has an even lower version: pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by Jheguy2** [comment]
Updated pip to 7.0.3 and removed the repo and tried the configuration script again. This error is the same on all machines I tried this fix on:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/OpenBazaar/node/openbazaar.py", line 16, in <module>
    import node.network_util as network_util
  File "node/network_util.py", line 5, in <module>
    import IPy
ImportError: No module named IPy

**Comment by gubatron** [comment]
tried doing:
`./env/bin/pip install IPy`

?

**Comment by gubatron** [comment]
basically try installing these manually, and if you get errors, paste errors here so we can find a way around them or determine the cause, maybe you have some major dependency issues.

**Comment by Jheguy2** [comment]
./env/bin/pip install IPy
Requirement already satisfied (use --upgrade to upgrade): IPy in ./env/lib/python2.7/site-packages

Should I try upgrading?

**Comment by gubatron** [comment]
ok, so what I think is going on here is that you're executing openbazaar using your system's python, and not the python inside `./env/bin`

**Comment by Jheguy2** [comment]
How do you suggest I fix this?

**Comment by gubatron** [comment]
(for one, you should probably not be running OpenBazaar as the root user)

try doing this:

`./env/bin/python2 -m node.openbazaar`

**Comment by gubatron** [comment]
the issue might be in how the `openbazaar` launching script detects your python, for some reason it's not using the one in the openbazaar environment.

**Comment by Jheguy2** [comment]
Thank you! The command:

./env/bin/python2 -m node.openbazaar

fixes my issue and launches OpenBazaar

**Comment by SamPatt** [comment]
>the issue might be in how the openbazaar launching script detects your python, for some reason it's not using the one in the openbazaar environment.

@gubatron How could folks test if this is their problem?

**Comment by gubatron** [comment]
@SamPatt the `openbazaar` launcher script changed quite a bit.
I'd need to see how it was morphed into what it is, the bug I think is def. on it.
Perhaps the last maintainer will be able to fix it faster.

It looks like this now:
```
#!/bin/sh

if [ "$(uname)" = Darwin ] ; then
  export DYLD_LIBRARY_PATH=$(brew --prefix openssl)/lib:$DYLD_LIBRARY_PATH
elif [ -f /etc/fedora-release ]; then
  export LD_LIBRARY_PATH=/opt/openssl-compat-bitcoin/lib:$LD_LIBRARY_PATH
fi

# if being executed from installation into some base directory,
# we make sure we are running standing at this location
if expr "$0" : '.*/bin/openbazaar$' > /dev/null ; then
  PYBASE=${0%/bin/openbazaar}/share/openbazaar
  (cd "$PYBASE" && python2 -m node.openbazaar "$@") &
else
  # openbazaar not installed in the system, trying local install
  # with virtual environment first
  if [ -f ./env/bin/python2 -a -r ./env/bin/python2 -a -x ./env/bin/python2 ] ; then
    ./env/bin/python2 -m node.openbazaar "$@" &
  else
    python -m node.openbazaar "$@" &
  fi
fi
```

I've no clue what the `if expr "$0" : '.*/bin/openbazaar$' > /dev/null ; then` is does, but my guess is that this is the branch of code executed causing the bug, instead of just going for the `./env/bin/python2`

Here's the 3 maintainers that touched there, any help would be appreciated.
![screen shot 2015-06-12 at 7 00 28 pm](https://cloud.githubusercontent.com/assets/163977/8141470/5f115170-1135-11e5-93f1-5f33b337362c.png)

CC: Charlie Root, @yurivict , @thomacer

**Comment by gubatron** [comment]
This is how things were last time I worked on it:

```
#!/bin/bash
# set -x
if [[ $OSTYPE == darwin* ]] ; then
  export DYLD_LIBRARY_PATH=$(brew --prefix openssl)/lib:${DYLD_LIBRARY_PATH}
fi

# if being executed from a ubuntu install out of /usr/bin
# we make sure we are standing at openbazaar's folder
# so we can make use of the virtual environment.
if [[ ${BASH_SOURCE[0]} == /usr/bin/openbazaar ]] ; then
  pushd /usr/share/openbazaar
fi

./env/bin/python node/openbazaar.py "$@" &

if [[ ${BASH_SOURCE[0]} == /usr/bin/openbazaar ]] ; then
  popd
fi
```

**Comment by SamPatt** [comment]
Thanks for your help @gubatron.

**Comment by hoffmabc** [comment]
Submitted a PR for this #1341 

Please pull code from there and see if it's still an issue. If not we can merge. 

@gubatron @Jheguy2
