### ISSUE TITLE
Broken on Ubuntu

### ISSUE THREAD

**Issue by yurivict** [OpenBazaar/OpenBazaar#1362]
I just tried on fresh Ubuntu (./configure.sh), and it doesn't listen on http port.

It appears to be broken on Arch as well.

**Comment by hoffmabc** [comment]
Ok I'll take a look tomorrow.

**Comment by yurivict** [comment]
It gets stuck at this: Generating PGP keypair. This may take several minutes...

**Comment by unsystemizer** [comment]
Search Issues for Generating PGP keypair

**Comment by yurivict** [comment]
Duplicate, reason is Ubuntu is starved of entropy.
