### ISSUE TITLE
Ability to edit contracts

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#137]
Right now the user can issue, republish, or remove contracts, but cannot edit them.

If we give them that option, it would essentially be taking the details from the old contract to create a new (slightly modified) one, publishing it, and deleting the old one. The user can do all of this in multiple steps, but having it done with a simple edit feature would be ideal.

I imagine before we have #123 finished we will need this for people to update prices, at the very least.

**Comment by SamPatt** [comment]
@hoffmabc I think I heard you say you're tackling this now?

**Comment by drwasho** [comment]
Editing contracts... completed by the mighty @hoffmabc 

@ChangeTip, send a bucket of nuts to @hoffmabc

**Comment by changetip** [comment]
Hi @hoffmabc, I've delivered a Bitcoin tip worth a bucket of nuts (100 bits) from @drwasho to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
