### ISSUE TITLE
Broken link in the wiki page

### ISSUE THREAD

**Issue by miguelrodriguesdossantos** [OpenBazaar/OpenBazaar#1381]
In [the wiki](https://github.com/OpenBazaar/OpenBazaar/wiki/), the link at the bottom should be pointing to [here](https://github.com/OpenBazaar/OpenBazaar/wiki/02.-Getting-Started) and not [here](https://github.com/OpenBazaar/OpenBazaar/wiki/Getting-Started).

**Comment by SamPatt** [comment]
Thank you, I've fixed.
