### ISSUE TITLE
Ability to add sales tax

### ISSUE THREAD

**Issue by robarada** [OpenBazaar/OpenBazaar#149]
Add an option to include a sales tax for certain addresses.

Depending on the location, many states in the US and other countries have started to require an online sales tax and sellers would want this feature in order to easily differentiate prices for different customers.

**Comment by SamPatt** [comment]
@drwasho, any thoughts on having an "additional costs" field added? Let's close this one.

**Comment by drwasho** [comment]
I opt for merchants to state that the price includes whatever additional costs there may be in the `description` field of the contract. Otherwise we need to display 2 prices and it becomes a mess.

**Comment by SamPatt** [comment]
Agreed.
