### ISSUE TITLE
Orders: Notification/indication that the notary has verified the contract

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#195]
I'm skipping the fact that there hasn't been a consensus selection of the notary (we're working on that), but when there is there should be a notification or text somewhere that the notary has approved the contract:

![0](http://s25.postimg.org/4n3cszx3j/Orders_tab.png)

**Comment by hoffmabc** [comment]
@drwasho @SamPatt we already display a notice to the user with the HUD notification that the Notary has approved it. Do we need an additional notice here?

**Comment by hoffmabc** [comment]
And it's in the UI for Orders page. I'm closing for now.
