### ISSUE TITLE
Notary address not showing up in 'contract details'... plus some other stuff

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#219]
Things not showing up:

1. Notary address
2. Avatar names in front of the addresses
3. Link out to their nodes?
4. Indication whether the nodes are online now. (bonus points)

![0](http://s22.postimg.org/p108kn3sh/Screenshot_from_2014_08_24_02_24_54.png)

**Comment by hoffmabc** [comment]
Added identicons.
