### ISSUE TITLE
How to report a scam to notary?

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#231]
Right now, how does a user contact a notary and let them know they need to take action to release funds, resolve disputes, whatever?

This relates to #192, because right now unless both sides use Bitmessage, there isn't a way to communicate. Also, I think having a formal way to "issue a complaint" or something would make folks much more comfortable.

**Comment by hoffmabc** [comment]
I'm closing because #192 supersedes this and we are already working on it. They can just message internally for now.
