### ISSUE TITLE
Add notary tipping option

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#256]
Basically will allow the users to leave a tip (equivalent to a miner's fee) to a notary, thereby incentivising the notary *profession*. I suggest that we have a field with a default value already set so that users have to change it to zero if they want to be cheap.

- If the merchant permits the tip, then the transaction releasing multisig funds to the merchant's nominated address should have an extra output to the notary minus the value of the tip.
- If the buyer permits the tip, then we the client should generate an unsigned transaction to the multisig address with an extra output to the notary.
- This system can be used to add charity tipping later down the road.

Something like:
![0](http://s25.postimg.org/4ui9hea8f/Issue02.png)

**Comment by hoffmabc** [comment]
Why are we tipping again? Can we just have tipping buttons on a user's profile or something?

**Comment by drwasho** [comment]
Agreed. I don't know what hell I was thinking.
