### ISSUE TITLE
Introducing Node Fee to OpenBazaar

### ISSUE THREAD

**Issue by Zadara** [OpenBazaar/OpenBazaar#268]
Introducing a node fee based on a percentage of the transaction will stimulate the decentralizing factor  of OpenBazaar. Instead of a voluntary system where the decentralizing factor will decrease as soon SPV clients will make their way to mainstream, with a node fee people will be rewarded for contributing to the network and will help anonymize the market.

My idea is to let every node insert their own bitcoin address. The node fee is based on a percentage of the transaction which sellers can adjust themselves so that sellers can decide how anonymous their ad should be. This amount of node fee is then distributed among the nodes following a table. In this table is kept record the time of every node since the last transaction. Nodes that were there hosting before the transaction would get the complete node fee and nodes that just stopped by halfway would get the half of the complete node fee.

Let me know what you guys think. Is this practical in combination with bitcoin or am I thinking way too theoretical? My technical understanding of bitcoin is a bit low.

**Comment by hoffmabc** [comment]
This is interesting but marking as out of scope so closing.
