### ISSUE TITLE
 Loading merchant... forever

### ISSUE THREAD

**Issue by Barthelemy** [OpenBazaar/OpenBazaar#384]
On my home page I click on Connected markets and then it says "Loading merchant" and nothing happens. 

I have upnp enabled in my modem and the port 12345 is forwarded according to what I see (I attach a screenshot). 

The program says : 
known_peers ['tcp://seed.bizarre.company:12345', 'tcp://seed.openlabs.co:12345', 'tcp://seed.openbazaar.org:12345', 'tcp://seed2.openbazaar.org:12345']
Searching for myself
Checking if port 8894 is free ...
Port 8894 is free!
Setting up UPnP Port Map Entry...
UPnP TCP P2P Port Map configuration done (12345 -> 12345) => True
UPnP UDP P2P Port Map configuration done (12345 -> 12345) => True
Started OpenBazaar Web App at http://127.0.0.1:8894
![capture d ecran 2014-09-03 a 20 53 05](https://cloud.githubusercontent.com/assets/4502689/4139536/b9953f62-339b-11e4-8b08-25184797f6cc.png)

How to debug this ? What could be the problem ?

Barth

**Comment by hoffmabc** [comment]
This is networking, which we're working on and will always be a problem sometimes depending on your network type.
