### ISSUE TITLE
when the socket listening on port 12345 crashes, notify the user/GUI instead of failing quietly

### ISSUE THREAD

**Issue by benemorius** [OpenBazaar/OpenBazaar#394]
Whenever the socket listening on port 12345 experiences `ERROR - Uncaught exception, closing connection.`, it results in a situation where the client is still interacting with the user on the port 8888 web interface, and (I presume) can still make outgoing connections, but is no longer accepting incoming connections from the network on port 12345.

This perhaps is a reason that nodes tend to not stay on the network for long periods of time right now. Or at least, I see it *appear* to happen a lot. A node which had been working suddenly is not reachable on port 12345. A restart of their client fixes it.

**Comment by hoffmabc** [comment]
Should be OBE with the new networking piece.
