### ISSUE TITLE
zeromq bug crashes python

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#412]
After I added a product with all details completed and a picture as icon, my python crashes completely at a system level. I think it's related to a zeromq pointer failure:

```
Bad file descriptor (bundled/zeromq/src/signaler.cpp:108)
```

When I re-ran OpenBazaar, I got the same crash without adding a product, but only after letting the daemon run for a while – the product had been stored and was already there in the web interface, which I managed to open before the crash.

Not sure if this is very reproducable, but we should keep it in mind.

This is on Mac OS X.

**Comment by hoffmabc** [comment]
Removing zeromq.
