### ISSUE TITLE
P2P Enhancements

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar#47]
I'm doing a thorough review of our p2p code and I'm beginning to think that our peer connection code is not scalable. In essence at the moment our nodes all need to be fully aware of every other node in the network. I'm exploring a transition to UDP (would get us around the firewall issues) and Kademlia for establishing a DHT that we could use for listings, reviews and peer discovery. I think this would allow us to have a small number of peers in our routing tables as well rather than requiring us to all maintain full peer tables the entire time. 

If you are not familiar with how this would work, essentially the seed node would wait for incoming join requests. When the first node came along they would join the seed node's network and ask for his routing table to kick it off. As the network expands each node has routing information for nodes closest to himself and less about the farther away nodes. Then they can traverse the network using these relationships. I'm extremely simplifying it, but I think this will provide much more scalability in the long term.

There are some issues with this approach, but I would argue that it's fairly resilient in general as proven by BitTorrent's use of this in their Mainline DHT. You can read some of the attacks that can be mounted here http://www.cs.helsinki.fi/u/lxwang/publications/security.pdf

Anyone have thoughts on this? I will be building this out on the Kademlia branch for now while I explore how this might work.

**Comment by SamPatt** [comment]
@hoffmabc, Can this be closed? Transition to RUDP nearly completed.
