### ISSUE TITLE
[UX/Wiki] "What is a Ricardian Contract" wiki page / link on OB home

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/OpenBazaar#530]
Just had a non techie install OpenBazaar and could see that a few links and tooltips will go along the way in teaching users how the product works (so far)

When they first come in, they ask them self "WTF is a Ricardian Contract", if they have the motivation to find out, a Google search doesn't yield very friendly results.

Can someone define what a Ricardian Contract is on the GitHub wiki, in a ***very user friendly way*** perhaps with a couple examples of what Ricardian Contracts can do? (I must admit I have no clue, and I just read on wikipedia about the economist after which the contracts are made after, but I don't get very much what these contracts mean for our context, other than they are contracts)

Being "Contracts" still at the top of the menues, it's probably important to have a link on that welcome message to that page on the Wiki.

@drwasho ?

**Comment by hoffmabc** [comment]
bump @drwasho

**Comment by drwasho** [comment]
Updated in the wiki... it's a start, more to come as the protocol is more formalized.
