### ISSUE TITLE
Native installation instructions (OSX, maybe more?)

### ISSUE THREAD

**Issue by Geekfish** [OpenBazaar/OpenBazaar#555]
This is another wiki related ticket.
It appears that the native installation instructions (at least for OSX) seem a bit out of date.

To elaborate, after trying to update the instructions for OSX, I run into the following:
* `./run.sh` currently tries to use python from a virtualenv that lies in `env/`. This doesn't match with the instructions that tell you to just create a virtualenv in your home dir under any desired name.
* A number of dependencies misbehave and may be missing from the instructions completely.
* A few minor instructions are out of date / clash with the quick startup guide.

I think that's not necessarily directly fixable and might actually be a bit of a waste of time to presently try to do so: `./configure.sh` kind of does everything you would want to do to install openbazaar, whether you want to just run it, test it, or develop it.
You can easily source the local `env/` virtualenv created by `./configure.sh` for development purposes while it's quite tricky to maintain up to date documentation on how to manually install all requirements before the required packages become relatively stable.

An idea would be just removing the native installation instructions and focusing on supporting issues that pop up when using the quick installation guide with `./configure.sh`.

**Comment by hoffmabc** [comment]
I'm closing since this has been improved.
