### ISSUE TITLE
ipv6-capable nodes can only see other ipv6-capable nodes

### ISSUE THREAD

**Issue by benemorius** [OpenBazaar/OpenBazaar#614]
The current state of ipv6 as of 0ccb956b51af870f91888e439a1db48c5007bb0e (which is yet unmerged) is that ipv6-**capable** nodes **must** use `./run.sh -i ${PUBLIC_IPV4_ADDRESS}` or else they will only be able to see other ipv6 nodes. Prior to this commit, it was required that they block ipv6 traffic at their firewall or hack the code, so this is slightly better now.

While this brings us one step closer to having ipv6-capable nodes not appear broken, we still aren't providing out-of-the-box success yet. I'm trying to see this all the way there in time for Beta 2 but I may have very little time available to do it.

The network is about 12% ipv6-capable by my last estimation and almost all of these users likely consider their nodes totally broken because they experience `only connected to seed markets` and `can't browse any markets`. An exception applies in the event that their ipv6 firewall lets port 12345 in: they **can** browse ipv6-capable seed.openlabs.co and any other ipv6 nodes with correctly configured firewalls, which at any one point in time right now is most often 0 - sometimes 1.

We ultimately need to fully support both ip stacks and follow best practices for doing so. I guess we need support for multiple uri's per guid. Actually, I haven't thought much about how to do this yet - neither short term hacks nor long term implementations. I've only recently taken full notice of the release schedule and realized a sense of urgency to resolve this quickly. I can't imagine the changes required will be appropriate to make during a feature freeze.

**Comment by hoffmabc** [comment]
Closing this for a later IPv6 issue.
