### ISSUE TITLE
Cross-platform desktop support via node-webkit

### ISSUE THREAD

**Issue by patcon** [OpenBazaar/OpenBazaar#648]
@SamPatt mentioned on IRC that some folks had been discussing this, and it is apparently a good approach to make desktop apps out of web tech, regardless of the specific web technology in use (ie. python).

This seems like a small sample of the approach:
http://blog.infireal.com/wsgi-node-webkit-2014-03.html

The node-webkit project has great supporting documentation:
https://github.com/rogerwang/node-webkit#readme

I don't think I'm the person to lead this effort, but it's still good to have an issue to coordinate discussion for all interested parties :)

**Comment by hoffmabc** [comment]
Using atom-shell (Electron) like @sirodoht mentioned.
