### ISSUE TITLE
Random choice of notaries or arbiters

### ISSUE THREAD

**Issue by AdamISZ** [OpenBazaar/OpenBazaar#649]
Follow up to IRC discussion:

(I will stick to arbiters in this although some/all may apply to notaries).

In this I assume that an arbiter is chosen by looking at the "acceptable arbiter" list for both buyer and seller, and is then chosen randomly from the intersecting set of the two (how is a null intersection dealt with?).

In order to avoid collusion between a buyer/seller and an arbiter, it's desirable that neither party can predict in advance which member of the intersecting set is chosen. For suppose that buyer B can predict which arbiter will be chosen for at least some sellers S1 ... Sn. Then he can deduce that for S3, his preferred colluding arbiter will be chosen, and he engages in the contract only with S3. 

This leads to the conclusion that whatever algorithm is used to choose the arbiter should not only be random, it should not be predictable by either counterparty before the contract is signed by all parties and committed to, and it must be verifiable by all parties after the event.

A natural choice would be hashes from a blockchain. This is possible, but the blockchain with the most reliable security (Bitcoin) has blocks released only every 10 minutes, which is too slow for these purposes (presumably?).

Another public source of randomness is the NIST public random beacon (https://beacon.nist.gov/rest/record/last) which releases a new 512 bit random number every 1 minute. There may be other similar sources, although I'm not aware of them. It's easy to grab ( I experimented with it here: https://github.com/AdamISZ/stegabank/blob/master/shared.py#L52-L63)

An important element in making this defence effective is the anti-Sybil element that there should be some meaningful (if small) cost to creating and then cancelling contracts. Also this defence is less effective if arbiters themselves can costlessly reject contracts - there's an assumption that arbiters accept contracts with anyone who asks for them.

A lot of this stuff I worked out in this protocol proposal: https://github.com/AdamISZ/stegabank/blob/master/protocol.md (it's long and not very relevant, so you can skip to the "Contract Negotiation" part, in particular the numbered list, for the most relevant bit, but some people might be interested in reading it all).

**Comment by drwasho** [comment]
I feel like we resolved this issue in the discussion and in other issues... which is more flexibility and power in the hands of the users to structure the terms of trade (notaries and arbiters).
