### ISSUE TITLE
IRS-compliant accounting CSV reports

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/OpenBazaar#679]
*Post 1.0 Release Todo Ticket, just so we don't forget and so we start getting people to help us on this*

[According to CPAs and Intuit](http://quickbooks.intuit.com/r/taxes/bitcoin-account-virtual-transactions) 

```"you need to keep track of the fair market value of your bitcoin transactions so that you can determine if you have a gain or loss on each one. If you purchase something with virtual currency that has a fair market value greater than the fair market value of the virtual currency, you will have a gain on the transaction, which will need to be reported on your tax return. By the same token, if the fair market value of the virtual property is greater than the item purchased, you will have a loss on the transaction, which also needs to be reported on your tax return."```

If I  understand correctly, Intuit's Quickbook allows for the implementation of Add-ons.
I have some ideas on enhancing the contracts specs to allow for sellers to determine a fiat currency to base the price of the good being sold, OpenBazaar could do a weighted average of the current exchange rate when the product is being browsed to present a Bitcoin price to the buyer.

Since the price information can easily be audited as it is public and it's very similar from the many sources (bitpay's, blockchain and endless other HTTP JSON feeds), once a transaction is started, notarized, paid for, and released, OpenBazaar must keep a record of the transaction in BTC, and along the entry it should include the base currency and exchange rate at the moment of purchase.

This information could be used to create a simple .csv file any developer can use to integrate with accounting software such as Quickbooks. It'd be a matter then of developing an OpenSource Quickbooks plugin, maybe even by us in the OpenBazaar community so that this information can easily be imported into the accounting workflow.

would love to hear your thoughts on this very important issue, we want to abide by the local tax laws, I understand this might be different depending on the jurisdiction, but I believe these pieces of information will be valuable regardless of what country you reside.

**Comment by hoffmabc** [comment]
If this issue has become about timestamping some fiat price into the Ricardian contract we should open a new issue for this @VivaLaPanda.
