### ISSUE TITLE
Shipping tracking information in physical goods contracts.

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/OpenBazaar#683]
Is there room in Ricardian contracts, more specifically for phisycal goods on the Double Signing step by the seller to optionally append:
 - Enum value representing a Shipping carrier (e.g.: UPS, USPS, FEDEX, DHL, etc)
 - Package tracking id

I believe with these 2 pieces of information, OpenBazaar (or extensions) could implement integration with the existing shipping tracking APIs of these companies.

https://www.usps.com/business/web-tools-apis/delivery-information.htm
https://www.ups.com/upsdeveloperkit/downloadresource?loc=en_US

If we then have a way to notify the seller and the buyer of successful shipping, we may reduce the number of disputes greatly. 

If we ever were to measure the average delay between the time of delivery and the time a buyer releases the escrow funds, I suppose a feature that would remind buyers to release funds timely would be awesome, and if the average delay could be quantified and made public, this could go towards a buyer's reputation (but in reality this would be hard to implement since not all packages will be tracked, and if they're tracked, maybe the seller could forget to put such information whe double signing the contract)

**Comment by drwasho** [comment]
Also related to issue #1317 in terms of adding additional semantic data to the contracts and having that supported in the client.

**Comment by Ignat99** [comment]
ok
