### ISSUE TITLE
[UX Design Idea] Specialized product creation via Template based Forms.

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/OpenBazaar#725]
Would love Wolf, @drwasho and @hoffmabc  to join this conversation as it pertains to contracts and user experience.
This is something that came to mind during one of my long runs.

I believe that depending on the contract one is about to create as a store owner, the openbazaar UI should give me the option to either do it my way, or to guide me by the hand, to make sure my product listing will be up to a normalized minimum listing standard.

Listing a book for sale, should be different than listing a tablet, and it'd be great if users browsing the network would browse product listings that wouldn't miss vital information for the shopper. This would in turn have huge efficiency savings in bandwidth and energy consumption by the network as there will be less back and forth between shoppers and buyers asking unnecessary questions.

If I'm to list a tablet for sale, I should be able to either create a custom contract (perhaps even let me as a seller to create my own contract listing templates) or search from a list of probably hundreds of product types users will be adding to the network.

So If I'm about to list a book, (which I think should be one of the first ones, if online books sales did it for amazon, they should also be a success on openbazaar), I should have a form that allows me to cover what users already expect to find when listing/buying a book:

Instead of just a title and a description, the UI for book listings should allow me to enter fields like:

```
Book Title [already in contract]
Condition: New | Used - Like New | Used - Very good | Used - Good [already in contract]
Book Author(s): string
ISBN: string
Number of Pages: int
Shipping Weight: float, Unit
Dimensions : float Vector[3], Unit
Synopsis : Text
Cover Picture : file | remote url
Year Published: int
Edition: string|int
```

I think this list of fields, and the possible data types/values they can have can be used to create UI-contract-templates that OpenBazaar could use to help the user enter products in an easy manner.

When a user is about to list a product, we should provide them with UI templates for the most common product types available out there, as well as not using any template, and just enter the most basic fields available to a contract, or load templates they may have downloaded from elsewhere.

***Where should this information go?***

From what I understand perhaps this information could go into a sub-section of the "contract" key in the ricardian contract object, and it would replace the "item_description" entry.

On the shopping end of things, OpenBazaar could easily read up a contract before displaying it on screen and dinamically create the user interface for the shopper browsing.

(this is a very rough idea, wanted to share it as it evolves, don't know if there's a similar conversation already taking place)

**Comment by drwasho** [comment]
This issue is now directly addressed in issue #1317.
