### ISSUE TITLE
"EOF occurred in violation of protocol"

### ISSUE THREAD

**Issue by Rav3nPL** [OpenBazaar/OpenBazaar#739]
OB freeze, gui not responging, console shows:
```
[Requests] error: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```
in log few of:
```
2014-10-04 21:54:41,237 - [1] CryptoPeerConnection - ERROR - Peer is not available for sending data
```

**Comment by hoffmabc** [comment]
Not sure why this was happening but haven't had reports of this since October so assuming this is a non-issue. Please open again @Rav3nPL if I'm jumping the gun.
