### ISSUE TITLE
Too many open connections/files

### ISSUE THREAD

**Issue by Rav3nPL** [OpenBazaar/OpenBazaar#748]
After about 3 hrs online my node get 43 stores connected and almost 1000 TCP connections to them.
Number of connections to every store vary from 10 to over 60.
I`m pretty sure, that one maybe two connections between nodes are enough to make it all working just fine.
It is easy to check:
```
$pidof python
9011
$lsof -p 9011|grep ESTABLISHED|wc -l
885
$lsof -p 9011|grep -i ipv4 |wc -l
974
```

I`m also not sure that "anon_inode" is, because it is almost another 1000 open files
```
python  9011 open 2117u  0000    0,9          0   6253 anon_inode

$lsof -p 9011|grep anon_inode|wc -l
959
```

Total number of open files:
```
$lsof -p 9011|wc -l
2042
```
It is about 75 just after start and connect to 3-4 stores.

**Comment by hoffmabc** [comment]
No longer present due to removal of ZMQ
