### ISSUE TITLE
Task: Notary and Arbitration Market

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#797]
The notary/arbitration tab has been blank for far too long. We need some means for users to explore **available** notaries and arbiters on the network for their trades. I suggest the following:

### Notary Market

![image](https://cloud.githubusercontent.com/assets/3887694/4621361/42122c4e-532a-11e4-91d3-aa2f6baaa565.png)

- Add a menu item called `Find Notaries`
  + When a user selects `Find Notaries`, a **search** is performed on the network for users that have enabled `Make me a notary`.
  + The name, *clickable* link to their node, notary description and an option to make the node a notary.
  + This means we'll need a place to describe notary services in the `Settings` page.

![image](https://cloud.githubusercontent.com/assets/3887694/4621496/1ef50856-532c-11e4-9b14-db3640278280.png)

### Arbiter Market
- Within the `Find Arbiters` in the `Arbitration` pull down menu: same as above (but for arbiters).

**Comment by rippler** [comment]
Is this going to find only those who are currently online?
That would make searches very time-sensitive. 
There's a proposal to allow users to post "Wanted" contracts, which would be a way for arbiters and notaries who aren't always online to look for opportunities.

**Comment by hoffmabc** [comment]
The current UI features a place for notaries to deal with this and arbiters are non-existent at this time so closing.
