### ISSUE TITLE
Auto-finalize feature?

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar#813]
We've been asked to consider an auto-finalize feature. Basically, the idea is to cut out the final step of buyers having to release funds once they receive the goods, and have an automatic time out if the buyer takes no action. From reddit:

>I think it would be important for OB to have auto-finalize functionality to release funds to the seller in cases where an item is marked shipped but the buyer never bothers to log back on to release funds or dispute the transaction.

I can see the benefits from this. Most online shoppers won't want to take any additional steps after they've ordered the product and paid for it, and it's a huge pain for the seller to have to work with the notary every single time the buyer doesn't respond.

However, it also makes scams much easier. If you can just wait out the buyer, you win. Obviously this can be mitigated by having some sort of flag for a buyer to raise if they never received a good, but I know personally I've bought many things that I forgot about until I received them in the mail.

Certainly there is room for improvement in how releasing funds works. Perhaps the client can track how long an order has gone without being marked as received, and prompt the user to answer whether or not they've received it once it reaches a week or something?

**Comment by hoffmabc** [comment]
@drwasho I don't know if I ever saw the continuation of thoughts on this one, but since the issue of MAD and finalization has come back up we should move discussion there. I will close this and reference issue #1314
