### ISSUE TITLE
Reputation Pledgeut field issues: symbol inside of input field, input field doesn't accept input

### ISSUE THREAD

**Issue by rippler** [OpenBazaar/OpenBazaar#837]
1. The Bitcoin currency symbol should be outside of input field
2. That field currently doesn't seem to accept input (probably unfinished code, in which case that's fine)

![screenhunter_07 oct 22 12 34](https://cloud.githubusercontent.com/assets/4045519/4731045/3eb2fc0a-59a5-11e4-8f65-4ee3be9138a4.jpg)

**Comment by hoffmabc** [comment]
I think this is fine for now and we can revisit during the GUI redesign.
