### ISSUE TITLE
Is it a endless loop bug or by design?

### ISSUE THREAD

**Issue by dong77** [OpenBazaar/OpenBazaar#902]
`CryptoTransportLayer`'s join_network method calls `dht.add_peer` method for each known peer, and inside `add_peer`, a new thread is created to execute `start_handshake`. However, in `CryptoPeerConnection`'s `start_handshake` method, `dht.add_peer` is called again if the peer has the same guid or address with an active peer. Therefore, it seems to me that the `add_peer` and `start_handshake` might get into a endless loop in some cases. Is is a bug or by design (if so why)?

**Comment by hoffmabc** [comment]
This activity is deprecated so closing.
