### ISSUE TITLE
Messaging and p2p network sub-system, stay with ZeroMQ or go with something like SnakeMQ?

### ISSUE THREAD

**Issue by El--Presidente** [OpenBazaar/OpenBazaar#904]
I cannot see why OB are using ZeroMQ. It is a nice flexible messaging queue but I believe it is overkill for OB and furthermore it is quite limited when it comes to network support.

SnakeMQ is pure python, much more lightweight but at the same time has some very desirable features such as:

1) Symmetric connections (You only need a single connection between peers and it doesn't matter who originates it - no need to establish two connections per peer (outbound and inbound) - straight away massively alleviate NAT problems for non-sellers.
2) Persistent queues (this is where messages get flushed to the database on shutdown and are retried next time the client is online/started)
3) Readily extendible network transport support
4) Simple abstracted messaging interface 

More at http://www.snakemq.net/

Obviously its a massive change but given the serious reworking that I think much of the p2p  and peer messaging needs I don't think it would result in an inordinate amount of additional effort and in the long run would lead to a smaller installation footprint and a much more flexible messaging framework which underpins just about every function in OpenBazaar.

**Comment by hoffmabc** [comment]
ZeroMQ has now been removed.
