### ISSUE TITLE
indentation error caused a bug? need your confirmation.

### ISSUE THREAD

**Issue by dong77** [OpenBazaar/OpenBazaar#906]
in https://github.com/OpenBazaar/OpenBazaar/blob/develop/node/dht.py line  213 and 219, these two lines should outdent to align with the if in line 193. Or am I wrong :)

Even if this is indeed a bug, I still think there is a missing 'else' for the 'if' in line 202 to handle 'found-exactly-that-node' situation and return just that node instead of close nodes.

**Comment by hoffmabc** [comment]
This is no longer relevant. Closing.
