### ISSUE TITLE
list mutation during iteration bug?

### ISSUE THREAD

**Issue by dong77** [OpenBazaar/OpenBazaar#907]
In file: https://github.com/OpenBazaar/OpenBazaar/blob/develop/node/dht.py
Line 246-250, 
```

            for idx, s in enumerate(self.searches):
                if s.findID == msg['findID']:
                    s.callback(msg['foundKey'])
                    if idx in self.searches:
                        del self.searches[idx]

```
 list is mutated while being iterated, this will cause some of the elements not being processed. I wrote this example to show the effect:

```
>>> ss = [1,2,3,4,5,6,7,8,9,10]
>>> for idx, s in enumerate(ss):
...   print s
...   if idx in ss:
...     del ss[idx]
...
1
2
4
5
7
9
10
```

**Comment by hoffmabc** [comment]
@Renelvon is working on refactor of the DHT code and this I don't believe is an issue any longer anyways @dong77. Feel free to open a new issue if it still persists for you.
