### ISSUE TITLE
Migrate existing UI to node-webkit

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#910]
Currently, the browser opens up pointed to the OpenBazaar URL. The first step towards the Beta 4.0 UI is to open up a node-webkit application.

* Make a simple node-webkit application
* Update the dependencies so that it can be ran without issues
* Make it open up by default when openbazaar starts

Please don't change any UI elements on the web interface yet. We'll do this in subsequent PRs.

**Comment by hoffmabc** [comment]
We will be moving to Electron so this is OBE.
