### ISSUE TITLE
JSON Ricardian contracts are not displaying multisig escrow details

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar#913]
The JSON Ricardian contract (found under the `Contract Details` tab) are not showing the multisignature escrow address or the redemption script.

Here is an example I pulled from seed.bizarre.company:

https://gist.github.com/drwasho/97a559dc229957800a92

**Comment by hoffmabc** [comment]
This is fixed as of 0.4

**Comment by drwasho** [comment]
![0](http://www.reactiongifs.com/r/mchi.gif)
