### ISSUE TITLE
Product page: Move mockup code to OpenBazaar codebase

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#923]
Contact @mwolf84 to get the mockup code for the product page, then make it part of the OpenBazaar codebase by copy/pasting the files in appropriate places. The page should be at a different URL for now, so that the old product page is also functional.

Don't hook up the new mockup to functionality yet: We just want it to exist as static HTML/CSS served from the OpenBazaar application.

**Comment by hoffmabc** [comment]
Closing per new UI work.
