### ISSUE TITLE
Search results page: Move mockup code to OpenBazaar codebase

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#925]
Contact @mwolf84 to get the mockup code for the search results page, then make it part of the OpenBazaar codebase by copy/pasting the files in appropriate places. The page should be at a different URL for now, so that the existing search results page is also functional.

Don't hook up the new mockup to functionality yet: We just want it to exist as static HTML/CSS served from the OpenBazaar application. The user doesn't need to be able to search for anything, just show some default product thumbnails.

**Comment by hoffmabc** [comment]
Closing per new UI work.
