### ISSUE TITLE
Buy modal: Move mockup code to OpenBazaar codebase

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#926]
Contact @mwolf84 to get the mockup code for the buy modal in the product page, then make it part of the OpenBazaar codebase by copy/pasting the files in appropriate places. The modal should be part of the new product URL, so Depends #923.

Don't hook up the modal to functionality yet: We just want it to exist as static HTML/CSS served from the OpenBazaar application. Just show a default product. However, you should hook it up so that the modal appears and disappears accordingly.

You should also make the modal navigable from wizard page to page, including the selection between 2-of-2 and 2-of-3 payment page, the product viewing page, and the checkout/payment page.

**Comment by hoffmabc** [comment]
Closing per new UI work.
