### ISSUE TITLE
New header: Move mockup code to OpenBazaar codebase

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#927]
Contact @mwolf84 to get the mockup code for the new header, then make it part of the OpenBazaar codebase by copy/pasting the files in appropriate places. The new header should not appear on old pages, but should affect #923 #924 #925. Please work with the developers responsible for these issues so that you can have the header as part of their pages.

Don't hook up the new mockup to functionality yet: We just want it to exist as static HTML/CSS served from the OpenBazaar application. The user doesn't need to be able to search for anything from the top-right search box. Navigation doesn't need to work either, just make it look correct and have semantic HTML/CSS.

**Comment by hoffmabc** [comment]
We are not moving this over yet as we are determining UI direction at the moment.
