### ISSUE TITLE
Buyer/Seller, Store Terminology

### ISSUE THREAD

**Issue by globalcitizen** [OpenBazaar/OpenBazaar#961]
https://github.com/OpenBazaar/OpenBazaar/wiki/Haggle-Protocol shows 'buyer' and 'seller' fields, plus code, documentation and issues refer to 'store' or 'merchant'.

In a real historical bazaar setting, trade is voluntary exchange of arbitrary assets, as in barter.

Perhaps it is worth removing the directional nature of assumed trade and replacing it with an even / decentralized conceptual paradigm / barter model.

This could also have legal implications, particularly under existing nation-state enforced taxation systems.

For some ideas around such an implementation see http://www.ifex-project.org/our-proposals/ifex in particular http://www.ifex-project.org/our-proposals/ifex/2012-04-11-partial-draft

**Comment by globalcitizen** [comment]
Ping. Is this architecture level issue being considered?

PS. Currently in Sydney, considering Brisbane... if you're about and keen for a chat let me know as I may visit before early/mid Feb.

**Comment by hoffmabc** [comment]
Sorry for the drop in conversation here. I think this while interesting I'm not sure I would advise we change direction completely to adopt this wholesale. Perhaps we could set up a discussion to hear your thoughts out though and see if maybe there is something that could be used @globalcitizen.

**Comment by drwasho** [comment]
I think that the terminology is going to be application-specific... so for the sale of physical goods for bitcoin, there will be a merchant and a buyer.

For services, that terminology won't be appropriate, so we'll use something better for that.
