### ISSUE TITLE
Market appearing twice

### ISSUE THREAD

**Issue by Barthelemy** [OpenBazaar/OpenBazaar#974]
I have a market "Default" that appears twice.
![capture d ecran 2014-11-09 a 12 41 18](https://cloud.githubusercontent.com/assets/4502689/4967270/678ac2c0-6805-11e4-83eb-905f398fa518.png)

I am on OSX Yosemite.

**Comment by hoffmabc** [comment]
I don't believe this occurs on 0.4.
