### ISSUE TITLE
Issue Starting up OpenBazaar post-0.3.0 update

### ISSUE THREAD

**Issue by ABISprotocol** [OpenBazaar/OpenBazaar#994]
Recent updates to OpenBazaar result in that the option to _./run.sh_ is no longer there (which worked before 0.3.0, whereas the _./openbazaar start_ command didn't work for me prior to 0.3.0), so now trying _./openbazaar start_ again
when I do ./openbazaar start the following error appears:
_Traceback (most recent call last):
  File "node/openbazaar.py", line 13, in <module>
    import psutil
ImportError: No module named psutil_
*Note that it ran ok before with ./run.sh (no longer available) on test box which had been Wubi installed on what used to be an XP-run box, with Wubi transitioned to Ubuntu12.04 LTS with a dual boot (and now is Ubuntu 14.04 LTS (still dual boot, not yet migrated Wubi install to partition)).*
Next step was to ./configure.sh (this had already been done, but thought I'd try it again)
It did some things including download Twisted==14.0.2 and during setup.py, it uninstalled 14.0.0 and went through various gyrations.
Eventually it ran setup.py install for psutil without me doing anything and it installed the _psutil_Linux extension and continued to do various gyrations and things, then it finished cleanly.
Again I went to ./openbazaar start
This time it started no problem.
_However,_
Pre-0.3.0, there was a nice message which appropriately characterized what to do for UPnP which said, in short, 
_Warning: UPnP was not setup correctly. Try doing a port forward on
12345 and start the node again with -j_
But now with 0.3.0 forward, a.t.m. it does not provide the error message telling you to port forward to 12345 and start the node again with -j, so I'd recommend adding that message back in somehow.
It provides only the following message:
_Exception : No UPnP device discovered
UPnP TCP P2P Port Map configuration done  (34053 -> 34053) => False
UPnP UDP P2P Port Map configuration done  (34053 -> 34053) => False
Warning: UPnP was not setup correctly.  Ports could not be automatically mapped.
Started OpenBazaar Web App at http://127.0.0.1:47378

(process:1044): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed_

This is probably a non-issue since it works and only requires that I set up port forward to complete the process successfully (nothing much needs to be changed), so I'm opening this primarily for documentation, if you have any problems note your box / OS type and describe.

**Comment by BitWaspBitWasp** [comment]
Can you help me ?
After ./openbazaar start I have these messages:

Setting up UPnP Port Map Entry...
Exception : No UPnP device discovered
UPnP TCP P2P Port Map configuration done (48490 -> 48490) => False
UPnP UDP P2P Port Map configuration done (48490 -> 48490) => False
Warning: UPnP was not setup correctly. Ports could not be automatically mapped.
Started OpenBazaar Web App at http://127.0.0.1:45378
Error occured while reset 800b: errno=5
Error occured while reset 800b: errno=5

**Comment by hoffmabc** [comment]
What kind of network are you on? Home network? NAT?

**Comment by BitWaspBitWasp** [comment]
Now I installed it on my server where I have hosting(clearnet)  for studying
and after that I want to install it in TOR network

-------- Original Message --------

**Comment by ABISprotocol** [comment]
@BitWaspBitWasp This (TOR with OpenBazaar) is discussed in another issue, I have some thoughts on it [here](https://github.com/OpenBazaar/OpenBazaar/issues/866#issuecomment-62577905).  It is particularly timely since Tails now includes an Electrum wallet. For reasons which I have described in the past and several studies which have revealed unmitigated vulnerabilities in this regard, I do not consider it advisable unless a user has no other choice.

**Comment by rippler** [comment]
On Windows, with 0.4 downloaded from Github:
```
PS C:\OpenBazaar> Traceback (most recent call last):
  File "C:\OpenBazaar\bin\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\OpenBazaar\bin\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\OpenBazaar\node\openbazaar.py", line 14, in <module>
    import psutil
ImportError: No module named psutil
```

**Comment by hoffmabc** [comment]
@ABISprotocol  This may be OBE now but there are a couple issues here being lumped together. First is the uPnP stuff at the top, which I think is related to 0.3 and we are now moved to a new networking structure so this should be retried. Later @rippler is mentioning a missing module named psutil which usually is a product of not running ./configure.sh. This module should installed during that process.
