### ISSUE TITLE
no public key for encryption after password set

### ISSUE THREAD

**Issue by bglassy** [OpenBazaar/OpenBazaar#997]
```[1] CryptoPeerConnection - WARNING - There is no public key for encryption```

Once you set a password in your storefront settings, the public key is not accessible for decryption until the node is restarted.

Perhaps we could add an additional warning to the password field so that users are informed that they need to restart or else the node will not function properly. The stop server option in advanced settings will not function after the password is set either.

**Comment by hoffmabc** [comment]
This is not an issue in 0.4+
