### ISSUE TITLE
Disconnected nodes don't update "connected stores"

### ISSUE THREAD

**Issue by soggypretzels** [OpenBazaar/OpenBazaar#999]
When leaving OB running in the background the number of connected stores increases as nodes are discovered, but the number will not decrease due to disconnected nodes until the page is refreshed.

Steps to reproduce:
Load OB and leave running for a while without user interaction (~10 min)
Refresh page or navigate to new page
Notice number of connected stores has dropped

Expected behavior:
OB should update the number connected nodes displayed to the user when nodes connect or disconnect, rather than only when they connect.

Running beta 3.0 in Windows 7 (64 bit) Palemoon

**Comment by hoffmabc** [comment]
We no longer count the number of connected nodes in the UI.
